infer_eval_metric: True
feature_transformers: {}
autogluon:
  predictor_init_kwargs: {}
  predictor_fit_kwargs:
    verbosity: 2
    presets: medium_quality
    time_limit: 300
    dynamic_stacking: False
llm:
  provider: openai
  api_key_location: OPENAI_API_KEY
  max_tokens: 512
  model: gpt-4-1106-preview
  # model: gpt-3.5-turbo
  proxy_url: null
  temperature: 0
  verbose: True